import { supabase } from "./supabase.js";

const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const money=v=>"₦"+Number(v||0).toLocaleString("en-NG");
const num=v=>Number(v||0).toLocaleString("en-NG");
const dt=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"})};
const norm=v=>String(v||"").trim().toLowerCase();
const cls=s=>["successful","success","approved","active","published","resolved"].includes(norm(s))?"success":["failed","rejected","dismissed","abandoned"].includes(norm(s))?"danger":["reviewing","in_review"].includes(norm(s))?"active":"pending";
const val=(r,ks,f="")=>{for(const k of ks)if(r?.[k]!==undefined&&r[k]!==null&&r[k]!=="")return r[k];return f};

const dashboardContent=$("#dashboardContent"),errorBox=$("#errorBox"),noticeBox=$("#noticeBox");
function err(m){errorBox.textContent=m;errorBox.style.display="block"}function clearErr(){errorBox.style.display="none";errorBox.textContent=""}
function notice(m){noticeBox.textContent=m;noticeBox.style.display="block";setTimeout(()=>noticeBox.style.display="none",3500)}
async function session(){const {data,error}=await supabase.auth.getSession();if(error)throw error;if(!data?.session?.user){location.href="account.html";return null}return data.session}
async function rpc(name,params={}){if(!await session())return null;const {data,error}=await supabase.rpc(name,params);if(error)throw error;return data}

function renderDashboard(d){
 const u=d.users||{},m=d.marketplace||{},p=d.payments||{},msg=d.messaging||{};
 const ru=Array.isArray(d.recent_users)?d.recent_users:[],rp=Array.isArray(d.recent_products)?d.recent_products:[];
 const sold=Number(m.sold_products??m.sold_listings??m.sold??0);
 const boostCount=Number(m.boosted_products??m.boosted_listings??p.boosted_count??0);
 const premiumCount=Number(m.premium_products??m.premium_listings??p.premium_count??0);
 dashboardContent.innerHTML=`<section class="cards">
 <article class="stat"><div class="stat-label">👥 Total Users</div><div class="stat-value blue">${num(u.total)}</div><div class="stat-note">Registered accounts</div></article>
 <article class="stat"><div class="stat-label">🏪 Sellers</div><div class="stat-value green">${num(m.total_sellers)}</div><div class="stat-note">Users with listings</div></article>
 <article class="stat"><div class="stat-label">📦 Total Listings</div><div class="stat-value purple">${num(m.total_products)}</div><div class="stat-note">All listings</div></article>
 <article class="stat"><div class="stat-label">🟢 Active Listings</div><div class="stat-value green">${num(m.active_products)}</div><div class="stat-note">Visible to buyers</div></article>
 <article class="stat"><div class="stat-label">🔴 Sold Listings</div><div class="stat-value red">${num(sold)}</div><div class="stat-note">Listings marked sold</div></article>
 <article class="stat"><div class="stat-label">🚗 High-Value Listings</div><div class="stat-value blue">${num(m.high_value_products)}</div><div class="stat-note">Successfully paid listings</div></article>
 <article class="stat"><div class="stat-label">🚀 Boosted Listings</div><div class="stat-value orange">${num(boostCount)}</div><div class="stat-note">Active boosted listings</div></article>
 <article class="stat"><div class="stat-label">👑 Premium Listings</div><div class="stat-value purple">${num(premiumCount)}</div><div class="stat-note">Active premium listings</div></article>
 <article class="stat"><div class="stat-label">💰 Listing Fee Revenue</div><div class="stat-value green">${money(p.listing_fee_revenue)}</div><div class="stat-note">Confirmed successful listing fees</div></article>
 <article class="stat"><div class="stat-label">🚀 Boost Revenue</div><div class="stat-value orange">${money(p.boost_revenue)}</div><div class="stat-note">Confirmed successful boost payments</div></article>
 <article class="stat"><div class="stat-label">👑 Premium Revenue</div><div class="stat-value purple">${money(p.premium_revenue)}</div><div class="stat-note">Confirmed successful premium payments</div></article>
 <article class="stat"><div class="stat-label">💳 Platform Revenue</div><div class="stat-value green">${money(p.successful_revenue)}</div><div class="stat-note">Confirmed successful payments</div></article></section>
 <section class="grid-2 section">
 <article class="panel"><div class="panel-head">👥 User Growth</div><div class="panel-body"><div class="mini-grid"><div class="mini"><div class="mini-label">7 days</div><div class="mini-value blue">${num(u.new_7_days)}</div></div><div class="mini"><div class="mini-label">30 days</div><div class="mini-value green">${num(u.new_30_days)}</div></div></div></div></article>
 <article class="panel"><div class="panel-head">💳 Payment Overview</div><div class="panel-body"><div class="mini-grid"><div class="mini"><div class="mini-label">Successful</div><div class="mini-value green">${num(p.successful_count)}</div></div><div class="mini"><div class="mini-label">Pending</div><div class="mini-value orange">${num(p.pending_count)}</div></div><div class="mini"><div class="mini-label">Listing fees</div><div class="mini-value green">${money(p.listing_fee_revenue)}</div></div><div class="mini"><div class="mini-label">Boost</div><div class="mini-value orange">${money(p.boost_revenue)}</div></div><div class="mini"><div class="mini-label">Premium</div><div class="mini-value purple">${money(p.premium_revenue)}</div></div></div></div></article>
 <article class="panel"><div class="panel-head">💬 Messaging</div><div class="panel-body"><div class="mini-grid"><div class="mini"><div class="mini-label">Conversations</div><div class="mini-value blue">${num(msg.conversations)}</div></div><div class="mini"><div class="mini-label">Messages</div><div class="mini-value">${num(msg.messages)}</div></div><div class="mini"><div class="mini-label">Unread</div><div class="mini-value orange">${num(msg.unread_messages)}</div></div></div></div></article>
 <article class="panel"><div class="panel-head">🔐 Current Fee Rules</div><div class="panel-body"><div class="mini-grid"><div class="mini"><div class="mini-label">Cars</div><div class="mini-value">${money(5000)}</div></div><div class="mini"><div class="mini-label">Land</div><div class="mini-value">${money(10000)}</div></div><div class="mini"><div class="mini-label">Houses/Apartments</div><div class="mini-value">${money(10000)}</div></div><div class="mini"><div class="mini-label">Commercial/Business</div><div class="mini-value">${money(15000)}</div></div></div></div></article></section>
 <section class="section"><div class="section-head"><h2>Recent Users</h2></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Email</th><th>User ID</th><th>Registered</th></tr></thead><tbody>${ru.length?ru.map(x=>`<tr><td>${esc(x.email||"No email")}</td><td class="muted">${esc(x.id||"")}</td><td>${dt(x.created_at)}</td></tr>`).join(""):'<tr><td colspan="3" class="empty">No users found.</td></tr>'}</tbody></table></div></div></section>
 <section class="section"><div class="section-head"><h2>Recent Listings</h2></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Listing</th><th>Category</th><th>Price</th><th>Status</th><th>Seller</th><th>Created</th></tr></thead><tbody>${rp.length?rp.map(x=>`<tr><td><strong>${esc(x.title||x.name||"Untitled")}</strong></td><td>${esc(x.category||"")}</td><td>${money(x.price)}</td><td><span class="badge ${cls(x.status)}">${esc(x.status||"unknown")}</span></td><td class="muted">${esc(x.seller_id||"")}</td><td>${dt(x.created_at)}</td></tr>`).join(""):'<tr><td colspan="6" class="empty">No listings found.</td></tr>'}</tbody></table></div></div></section>`;
 $("#lastUpdated").textContent="Last updated: "+new Date().toLocaleString("en-NG");
}
async function loadAdmin(){dashboardContent.innerHTML='<div class="loading">Loading dashboard...</div>';try{renderDashboard(await rpc("admin_dashboard_v2")||{})}catch(e){dashboardContent.innerHTML="";err(e.message||"Unable to load dashboard.")}}

async function loadListingPayments(){
 const el=$("#listingPaymentsList");el.innerHTML='<tr><td colspan="7" class="loading">Loading listing payments...</td></tr>';
 try{const rows=await rpc("admin_listing_payments_v2")||[];if(!rows.length){el.innerHTML='<tr><td colspan="7" class="empty">No confirmed high-value listing payments found.</td></tr>';return}
 el.innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.product_title||"Untitled")}</strong><br><span class="muted">${esc(r.product_id||"")}</span></td><td>${esc(r.category||"")}<br><span class="badge">${esc(r.listing_type||"")}</span></td><td>${esc(r.seller_email||r.seller_id||"")}</td><td><strong class="green">${money(r.amount)}</strong></td><td><span class="badge ${cls(r.status)}">${esc(r.status||"unknown")}</span></td><td class="muted">${esc(r.paystack_reference||"")}</td><td>${dt(r.created_at)}</td></tr>`).join("")
 }catch(e){el.innerHTML=`<tr><td colspan="7" class="empty">Could not load listing payments.<br><br>${esc(e.message||e)}</td></tr>`}
}
async function loadPromotionPayments(){
 const el=$("#promotionPaymentsList");el.innerHTML='<tr><td colspan="7" class="loading">Loading promotion payments...</td></tr>';
 try{const rows=await rpc("admin_promotion_payments_v2")||[];if(!rows.length){el.innerHTML='<tr><td colspan="7" class="empty">No boost or premium payments found.</td></tr>';return}
 el.innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.product_title||r.title||"Listing")}</strong><br><span class="muted">${esc(r.product_id||"")}</span></td><td><span class="badge ${norm(r.promotion_type)==="premium"?"success":"active"}">${esc(r.promotion_type||"unknown")}</span></td><td>${esc(r.seller_email||r.seller_id||"")}</td><td><strong>${money(r.amount)}</strong></td><td><span class="badge ${cls(r.status)}">${esc(r.status||"unknown")}</span></td><td class="muted">${esc(r.paystack_reference||r.reference||"")}</td><td>${dt(r.created_at)}</td></tr>`).join("")
 }catch(e){el.innerHTML=`<tr><td colspan="7" class="empty">Could not load boost/premium payments.<br><br>${esc(e.message||e)}</td></tr>`}
}
async function loadReports(){
 const el=$("#reportsList");el.innerHTML='<div class="loading">Loading reports...</div>';
 try{const d=await rpc("admin_reports_overview"),all=Array.isArray(d)?d:(d?.reports||d?.recent||d?.items||d?.data||[]),f=$("#reportStatusFilter").value,rows=f==="all"?all:all.filter(r=>norm(r.status)===f);$("#reportCount").textContent=num(rows.length);if(!rows.length){el.innerHTML=`<div class="empty">No ${f==="all"?"":f+" "}reports found.</div>`;return}
 el.innerHTML=rows.map(r=>{const id=val(r,["id","report_id"]),status=val(r,["status"],"pending"),reason=val(r,["reason","report_reason"],"No reason supplied"),type=val(r,["report_type","type"],"Report"),reporter=val(r,["reporter_email","reporter_name","reporter_id","user_id"],"Unknown"),listing=val(r,["listing_title","product_title","title"],""),target=val(r,["reported_user_email","reported_user_name","reported_user_id","target_user_id"],"");return `<div class="row"><div><strong>Report #${esc(id)} — ${esc(type)}</strong><div class="meta"><strong>Reason:</strong> ${esc(reason)}<br>${listing?`Listing: ${esc(listing)}<br>`:""}${target?`Reported user: ${esc(target)}<br>`:""}Reporter: ${esc(reporter)}<br>Created: ${dt(val(r,["created_at","reported_at"]))}</div></div><div class="actions"><span class="badge ${cls(status)}">${esc(status)}</span><select class="filter report-status"><option value="">Change status…</option><option value="pending">Pending</option><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select><input class="filter report-note" placeholder="Admin note"><button class="btn small primary update-report" data-id="${esc(id)}">Update report</button></div></div>`}).join("");
 el.querySelectorAll(".update-report").forEach(b=>b.onclick=async()=>{const row=b.closest(".row"),s=row.querySelector(".report-status").value,n=row.querySelector(".report-note").value.trim();if(!s){err("Choose a new report status first.");return}b.disabled=true;try{await rpc("admin_update_report",{p_report_id:b.dataset.id,p_status:s,p_admin_note:n});notice("Report updated successfully.");await loadReports()}catch(e){err(e.message||"Could not update report.")}finally{b.disabled=false}})
 }catch(e){el.innerHTML="";$("#reportCount").textContent="!";err(e.message||"Unable to load reports.")}
}
async function loadVerifications(){
 const el=$("#verificationsList");el.innerHTML='<div class="loading">Loading verification requests...</div>';
 try{const d=await rpc("admin_seller_verifications_overview"),rows=Array.isArray(d?.requests)?d.requests:(Array.isArray(d)?d:[]),sum=d?.summary||{};$("#verifyPending").textContent=num(sum.pending??rows.filter(r=>norm(r.status)==="pending").length);$("#verifyApproved").textContent=num(sum.approved??rows.filter(r=>norm(r.status)==="approved").length);$("#verifyRejected").textContent=num(sum.rejected??rows.filter(r=>norm(r.status)==="rejected").length);const f=$("#verificationFilter").value,a=f==="all"?rows:rows.filter(r=>norm(r.status)===f);if(!a.length){el.innerHTML=`<div class="empty">No ${f==="all"?"":f+" "}verification requests.</div>`;return}
 el.innerHTML=a.map(r=>{const id=r.id,s=norm(r.status||"pending");return `<div class="row"><div><strong>Verification #${esc(id)} — ${esc(r.full_name||"Unknown seller")}</strong><div class="meta">Seller type: ${esc(r.seller_type||"individual")}<br>Phone: ${esc(r.phone||"—")}<br>Business: ${esc(r.business_name||"—")}<br>ID type: ${esc(r.id_type||"—")}<br>Submitted: ${dt(r.created_at)}${r.seller_note?`<br>Seller note: ${esc(r.seller_note)}`:""}${r.document_path?`<br><button class="btn small doc" data-id="${esc(id)}">View document</button>`:""}</div></div><div class="actions"><span class="badge ${cls(s)}">${esc(s)}</span>${s==="pending"?`<button class="btn small primary approve" data-id="${esc(id)}">Approve Seller</button><button class="btn small danger reject" data-id="${esc(id)}">Reject Seller</button>`:""}</div></div>`}).join("");
 el.querySelectorAll(".doc").forEach(b=>b.onclick=async()=>{try{const d=await rpc("admin_get_seller_verification_document",{p_verification_id:b.dataset.id});if(!d?.url)throw new Error("Document URL was not returned.");window.open(d.url,"_blank","noopener,noreferrer")}catch(e){err(e.message||"Could not open document.")}});
 el.querySelectorAll(".approve,.reject").forEach(b=>b.onclick=async()=>{const s=b.classList.contains("approve")?"approved":"rejected";b.disabled=true;try{const d=await rpc("admin_update_seller_verification",{p_verification_id:b.dataset.id,p_status:s,p_admin_note:null});if(d?.success===false)throw new Error(d.message||"Update failed.");notice(s==="approved"?"Seller approved successfully.":"Seller rejected successfully.");await loadVerifications()}catch(e){err(e.message||"Could not update verification.")}finally{b.disabled=false}})
 }catch(e){el.innerHTML=`<div class="empty">Could not load verification requests.<br><br>${esc(e.message||e)}</div>`}
}
async function loadNotifications(){
 try{await session();const {data,error}=await supabase.from("admin_notifications").select("*").order("created_at",{ascending:false}).limit(100);if(error)throw error;const rows=Array.isArray(data)?data:[],unread=rows.filter(x=>x.is_read!==true).length;$("#notificationBadge").textContent=unread?unread:"";$("#notificationList").innerHTML=rows.length?rows.map(n=>`<div class="notification-item ${n.is_read?"":"unread"}" data-id="${esc(n.id)}"><strong>${esc(n.title||n.type||"AjeMarket notification")}</strong><div class="notification-body">${esc(n.message||n.body||n.details||n.reason||"")}</div><small class="muted">${dt(n.created_at)}</small></div>`).join(""):'<div class="empty">No notifications yet.</div>';$("#notificationList").querySelectorAll(".notification-item").forEach(i=>i.onclick=async()=>{try{await rpc("admin_mark_notification_read",{p_notification_id:i.dataset.id});await loadNotifications()}catch(e){err(e.message)}})
 }catch(e){$("#notificationList").innerHTML=`<div class="empty">Could not load notifications.<br><br>${esc(e.message||e)}</div>`}
}
async function markAll(){try{await rpc("admin_mark_all_notifications_read");await loadNotifications()}catch(e){err(e.message||"Unable to mark notifications read.")}}
async function refreshAll(){clearErr();await Promise.all([loadAdmin(),loadListingPayments(),loadPromotionPayments(),loadReports(),loadVerifications(),loadNotifications()])}
$("#refreshBtn").onclick=async()=>{const b=$("#refreshBtn");b.disabled=true;b.textContent="Loading...";try{await refreshAll()}finally{b.disabled=false;b.textContent="Refresh"}};
$("#refreshPaymentsBtn").onclick=loadListingPayments;$("#refreshPromotionPaymentsBtn").onclick=loadPromotionPayments;$("#refreshVerificationsBtn").onclick=loadVerifications;$("#verificationFilter").onchange=loadVerifications;$("#reportStatusFilter").onchange=loadReports;$("#loadReportsBtn").onclick=loadReports;
$("#notificationBtn").onclick=async()=>{const p=$("#notificationPanel");p.style.display=p.style.display==="block"?"none":"block";if(p.style.display==="block")await loadNotifications()};$("#closeNotificationsBtn").onclick=()=>$("#notificationPanel").style.display="none";$("#markAllReadBtn").onclick=markAll;
$("#logoutBtn").onclick=async()=>{try{await supabase.auth.signOut();location.href="account.html"}catch(e){err(e.message)}};
(async()=>{try{await refreshAll()}catch(e){err(e.message||"Unable to initialize admin dashboard.")}})();
setInterval(()=>{if(document.visibilityState==="visible")refreshAll().catch(console.warn)},30000);
